### ISSUE TITLE
doy in get_temporal_predictors is day of month

### ISSUE THREAD

**Issue by buzacott** [stanfordmlgroup/methane-gapfill-ml#14]
`timestamp.dt.day` returns the day of the month rather than the day of the year, and subsequently the sin/cos variables do not represent a yearly signal
https://github.com/stanfordmlgroup/methane-gapfill-ml/blob/c3645e62aaf38dfb8abdafa5ddc26579f27cfc7b/fluxgapfill/predictors/process.py#L35-L37

rather it should be `timestamp.dt.dayofyear`, e.g.

```python 
>>> df = pd.DataFrame({'timestamp': [dt.datetime(2022, 12, 1)]})
>>> df['timestamp'].dt.day
0    1
Name: timestamp, dtype: int64
>>> df['timestamp'].dt.dayofyear
0    335
Name: timestamp, dtype: int64
```

**Comment by jirvin16** [comment]
Thank you for raising this! @ylzhouchris let's fix this?

Note that this did not affect the associated Agricultural and Forest Meteorology paper which used a separate codebase (and I have verified that day of year is correctly used there). This bug was introduced when simplifying that codebase in the development of this one.

**Comment by gavinmcnicol** [comment]
Thank you, this bug should be fixed now.
